#!/usr/bin/env bash
# =====================================================================
#  seal_t3t4.sh - T3/T4 evidence sealing (SHA256SUMS generator, Linux)
#
#  Linux counterpart of seal_t3t4.ps1 -- same entry set, same order:
#    A: every file under evidence/ (recursive, excluding the manifest)
#    B: tool + docs + scripts
#    C: inject toolchain artifacts (baseline + official + derived)
#  Emits evidence/SHA256SUMS_T3T4.txt in sha256sum format (LF, ascii).
#  Re-runnable; the output file itself is excluded from the manifest.
#
#  NOTE: text artifacts generated by the Windows toolchain carry CRLF
#  line endings; the copies committed to git are LF (normalized on
#  commit), so this Linux manifest hashes the LF form.  Binary artifacts
#  (cubin) hash identically on both platforms -- see
#  test/SM120_L2_LINUX.md (reproduction matrix).
#
#  Usage:
#    ./seal_t3t4.sh
# =====================================================================
set -eu
export LC_ALL=C

GEN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$GEN_DIR/../.." && pwd)"
SUMS="$GEN_DIR/evidence/SHA256SUMS_T3T4.txt"

rel() { printf '%s\n' "${1#$REPO_ROOT/}"; }
add() {
    local full="$REPO_ROOT/$1"
    if [ -f "$full" ]; then
        printf '%s  %s\n' "$(sha256sum "$full" | cut -d' ' -f1)" "$1"
    else
        printf '# MISSING: %s\n' "$1"
    fi
}

{
    # ---- A: every file under evidence/ (except the sums file itself) ----
    find "$GEN_DIR/evidence" -type f ! -name 'SHA256SUMS_T3T4.txt' -print0 \
        | sort -z \
        | while IFS= read -r -d '' f; do
              printf '%s  %s\n' "$(sha256sum "$f" | cut -d' ' -f1)" "$(rel "$f")"
          done

    # ---- B: tool + docs + scripts ----
    for p in \
        'tools/instrument/extract_sass.py' \
        'tools/instrument/README.md' \
        'test/sm120_l2_gen/T3_REPORT.md' \
        'test/sm120_l2_gen/T4_REPORT.md' \
        'test/sm120_l2_gen/run_all_t3t4.ps1' \
        'test/sm120_l2_gen/run_all_t3t4.sh' \
        'test/sm120_l2_gen/seal_t3t4.ps1' \
        'test/sm120_l2_gen/seal_t3t4.sh'
    do add "$p"; done

    # ---- C: inject toolchain artifacts (baseline + official + derived) ----
    for p in \
        'platforms/cuda/hal/inject/Makefile' \
        'platforms/cuda/hal/inject/make_msvc.bat' \
        'platforms/cuda/hal/inject/inject.cu' \
        'platforms/cuda/hal/inject/inject_120.cubin' \
        'platforms/cuda/hal/inject/inject_120.asm' \
        'platforms/cuda/hal/inject/inject_120_cc.asm' \
        'platforms/cuda/hal/inject/inject_120.json' \
        'platforms/cuda/hal/inject/inject_86.cubin' \
        'platforms/cuda/hal/inject/inject_86.asm' \
        'platforms/cuda/hal/inject/inject_86_cc.asm' \
        'platforms/cuda/hal/inject/inject_86.json' \
        'platforms/cuda/hal/inject/inject_sm86.asm' \
        'platforms/cuda/hal/src/arch/sm86.cpp'
    do add "$p"; done
} > "$SUMS"

echo "sealed: $(wc -l < "$SUMS") entries -> $SUMS"
