// =====================================================================
//  sm120.cpp - Level-2 (guardian) instruction arrays for Blackwell sm_120
//
//  Generated by tools/instrument/extract_sass.py (T4) from
//  platforms/cuda/hal/inject/inject.cu compiled with
//  nvcc 12.9.41 / ptxas 12.9.41 (-arch sm_120 -m 64 -astoolspatch),
//  then manually reviewed instruction-by-instruction (T5).  Review:
//  test/sm120_mve/T5_REVIEW.md; golden regression: test/sm120_l2_gen/.
//
//    guardian (50 instrs, BSYNC-reconverged at +0x310):
//      LDC R4/R5 @ c[0x0][0x170/0x174]  preempt buffer pointer
//      LDC R6/R7 @ c[0x0][0x180/0x184]  kernel idx
//      (debugger-parameters window c[0x0][0x170..0x188], T1-verified)
//    resume   (32 instrs, keeps the RET.ABS.NODEC R20 exit):
//      LDC R4/R5 @ c[0x0][0x170/0x174]  preempt buffer pointer
//      LDC R20/R21 @ c[0x0][0x178/0x17c]  jump-back entry point
//
//  Resource requirements (T3 review): RequiredRegs = 32, RequiredBarriers = 1.
//
//  Regenerate:
//    cd platforms/cuda/hal/inject && make_msvc.bat ARCH=120 bin dump cc
//    python tools/instrument/extract_sass.py generate --cubin inject_120.cubin
//        --source inject.cu --offset-map sm120 --out-cubin <verify>.cubin
// =====================================================================

#include <cstring>

#include "xsched/utils/log.h"
#include "xsched/utils/xassert.h"
#include "xsched/cuda/hal/arch/sm120.h"
#include "xsched/cuda/hal/common/driver.h"

using namespace xsched::cuda;

#define INSTR_LEN 16

// sm120 trap-handler return stub entry (reported as the +0x18 field of the
// export-table slot-20 info).  Every trap-handler exit path converges on this
// stub, which starts with two NOPs followed by cache invalidation and
// RET.ABS R12 0x20; the first NOP is the patch site.
static constexpr size_t kTrapPatchOffset = 0x880;

void GuardianSM120::GetGuardianInstructions(const void **guardian_instr, size_t *size)
{
    static const uint64_t guardian_instructions[] =
    {
        0x0000031000007945, 0x000fe80003800200, // BSSY.RECONVERGENT B0, 0x310
        0x00005c00ff047b82, 0x000fc00000000800, // LDC R4, c[0x0][0x170]
        0x00005d00ff057b82, 0x000fc00000000800, // LDC R5, c[0x0][0x174]
        0x0000000000007919, 0x000e220000002500, // S2R R0, SR_CTAID.X
        0x0000dd00ff037b82, 0x000e220000000800, // LDC R3, c[0x0][0x374]
        0x0000000000087919, 0x000e220000002600, // S2R R8, SR_CTAID.Y
        0x00000000000a7919, 0x000e620000002100, // S2R R10, SR_TID.X
        0x00000000000b7919, 0x000e620000002200, // S2R R11, SR_TID.Y
        0x0000000000097919, 0x000ea20000002700, // S2R R9, SR_CTAID.Z
        0x0000000300007224, 0x001fe400078e0208, // IMAD R0, R0, R3, R8
        0x0000000000087919, 0x000e620000002300, // S2R R8, SR_TID.Z
        0x0000de00ff037b82, 0x000ea40000000800, // LDC R3, c[0x0][0x378]
        0x0000000300007224, 0x004fca00078e0209, // IMAD R0, R0, R3, R9
        0x0000000400097810, 0x000fe40007ffe000, // IADD3 R9, PT, PT, R0, 0x4, R0
        0x0000000a08ff7212, 0x002fc6000780fe0b, // LOP3.LUT P0, RZ, R8, R10, R11, 0xfe, !PT
        0x0000000409087825, 0x000fd400078e0004, // IMAD.WIDE.U32 R8, R9, 0x4, R4
        0x0000000000680947, 0x000fea0003800000, // @P0 BRA 0x2b0
        0x0000000004007980, 0x000ea20000100900, // LD.E R0, [R4]
        0x0000013000017945, 0x000fe20003800200, // BSSY.RECONVERGENT B1, 0x260
        0x000000ff0000720c, 0x004fda0003f05270, // ISETP.NE.AND P0, PT, R0, RZ, PT
        0x0000000008008385, 0x0001e200001009ff, // @!P0 ST.E [R8], RZ
        0x00000000003c8947, 0x000fea0003800000, // @!P0 BRA 0x250
        0x00006000ff067b82, 0x000fc00000000800, // LDC R6, c[0x0][0x180]
        0x00006100ff077b82, 0x000fc00000000800, // LDC R7, c[0x0][0x184]
        0x00000001ff037431, 0x000fca00000001ff, // HFMA2 R3, -RZ, RZ, 0, 5.9604644775390625e-08
        0x0000000008007385, 0x0003e80000100903, // ST.E [R8], R3
        0x00000008040a7980, 0x000ea20000100b00, // LD.E.64 R10, [R4+0x8]
        0x0000008000027945, 0x000fe20003800100, // BSSY.RELIABLE B2, 0x240
        0x000000ff0a00720c, 0x004fdc0003f15270, // ISETP.NE.S64.AND P0, PT, R10, RZ, PT
        0x0000000000108947, 0x002fea0003800000, // @!P0 BRA 0x220
        0x000000060a00720c, 0x000fdc0003f15270, // ISETP.NE.S64.AND P0, PT, R10, R6, PT
        0x0000000000020942, 0x000fea0003800100, // @P0 BREAK.RELIABLE B2
        0x0000000000088947, 0x000fea0003800000, // @!P0 BRA 0x230
        0x00000000000c7947, 0x000fea0003800000, // BRA 0x250
        0x0000000804007385, 0x0003e40000100b06, // ST.E.64 [R4+0x8], R6
        0x0000000000027941, 0x000fea0003800100, // BSYNC.RELIABLE B2
        0x0000000408007385, 0x0005e40000100903, // ST.E [R8+0x4], R3
        0x0000000000017941, 0x000fea0003800200, // BSYNC.RECONVERGENT B1
        0x00000000fffff984, 0x000fe20000000800, // @!PT LDS RZ, [RZ]
        0x00000000fffff984, 0x000fe20000000800, // @!PT LDS RZ, [RZ]
        0x00000000fffff984, 0x000fe20000000800, // @!PT LDS RZ, [RZ]
        0x00000000fffff984, 0x000fe20000000800, // @!PT LDS RZ, [RZ]
        0x0000000000007992, 0x000fec0000000000, // MEMBAR.SC.CTA
        0x0000000000007948, 0x000fea0003800000, // WARPSYNC.ALL
        0x0000000000007918, 0x000fe20000000000, // NOP
        0x0000000000007b1d, 0x000fec0000010000, // BAR.SYNC.DEFER_BLOCKING 0x0
        0x0000000008087980, 0x005ea40000100900, // LD.E R8, [R8]
        0x000000ff0800720c, 0x004fda0003f05270, // ISETP.NE.AND P0, PT, R8, RZ, PT
        0x000000000000094d, 0x000fea0003800000, // @P0 EXIT
        0x0000000000007941, 0x000fea0003800200, // BSYNC.RECONVERGENT B0
    };
    *guardian_instr = guardian_instructions;
    *size = sizeof(guardian_instructions);
}

void GuardianSM120::GetResumeInstructions(const void **resume_instr, size_t *size)
{
    static const uint64_t resume_instructions[] =
    {
        0x0000015000007945, 0x000fe80003800200, // BSSY.RECONVERGENT B0, 0x150
        0x00005c00ff047b82, 0x000fc00000000800, // LDC R4, c[0x0][0x170]
        0x00005d00ff057b82, 0x000fc00000000800, // LDC R5, c[0x0][0x174]
        0x0000000000007919, 0x000e220000002500, // S2R R0, SR_CTAID.X
        0x0000dd00ff037b82, 0x000e220000000800, // LDC R3, c[0x0][0x374]
        0x0000000000067919, 0x000e220000002600, // S2R R6, SR_CTAID.Y
        0x0000000000087919, 0x000e6c0000002700, // S2R R8, SR_CTAID.Z
        0x0000de00ff077b82, 0x000e620000000800, // LDC R7, c[0x0][0x378]
        0x0000000300007224, 0x001fc800078e0206, // IMAD R0, R0, R3, R6
        0x0000000700007224, 0x002fca00078e0208, // IMAD R0, R0, R7, R8
        0x0000000500037810, 0x000fca0007ffe000, // IADD3 R3, PT, PT, R0, 0x5, R0
        0x0000000403047825, 0x000fca00078e0004, // IMAD.WIDE.U32 R4, R3, 0x4, R4
        0x0000000004007980, 0x000ea40000100900, // LD.E R0, [R4]
        0x000000ff0000720c, 0x004fda0003f05270, // ISETP.NE.AND P0, PT, R0, RZ, PT
        0x000000000000894d, 0x000fea0003800000, // @!P0 EXIT
        0x0000000000007948, 0x000fea0003800000, // WARPSYNC.ALL
        0x0000000000007918, 0x000fe20000000000, // NOP
        0x0000000000007b1d, 0x000fec0000010000, // BAR.SYNC.DEFER_BLOCKING 0x0
        0x0000000004007385, 0x0001e200001009ff, // ST.E [R4], RZ
        0x00005e00ff147b82, 0x000fc00000000800, // LDC R20, c[0x0][0x178]
        0x00005f00ff157b82, 0x000fc00000000800, // LDC R21, c[0x0][0x17c]
        0x0000000000007941, 0x000fea0003800200, // BSYNC.RECONVERGENT B0
        0x0000000014007950, 0x001fea0003e00000, // RET.ABS.NODEC R20 0x0
        0xfffffffc00fc7947, 0x000fc0000383ffff, // BRA 0x170 (self)
        0x0000000000007918, 0x000fc00000000000, // NOP
        0x0000000000007918, 0x000fc00000000000, // NOP
        0x0000000000007918, 0x000fc00000000000, // NOP
        0x0000000000007918, 0x000fc00000000000, // NOP
        0x0000000000007918, 0x000fc00000000000, // NOP
        0x0000000000007918, 0x000fc00000000000, // NOP
        0x0000000000007918, 0x000fc00000000000, // NOP
        0x0000000000007918, 0x000fc00000000000, // NOP
    };
    *resume_instr = resume_instructions;
    *size = sizeof(resume_instructions);
}

// =====================================================================
//  TarpHandlerSM120 - Level-3 (trap) support for Blackwell sm_120.
//
//  Source: inject.cu::check_preempt_trap, regenerated by
//  tools/instrument/extract_sass.py (nvcc 12.9.41 / ptxas 12.9.41,
//  --offset-map sm120, trim=none), then composed mirroring the reviewed
//  sm86 trap array: the leading BSSY.RECONVERGENT B0 pair and the trailing
//  [BSYNC B0, RET.ABS, BRA, NOP fill] are dropped so that the "no-preempt"
//  branches (target .L_x_21) land exactly on the appended
//  [replaced instruction + jump-back] block.
// =====================================================================
static const uint64_t trap_inject_instrs[] =
{
    0x00005c00ff047b82, 0x000fc00000000800, // LDC R4, c[0x0][0x170]
    0x00005d00ff057b82, 0x000fc00000000800, // LDC R5, c[0x0][0x174]
    0x00006000ff067b82, 0x000fc00000000800, // LDC R6, c[0x0][0x180]
    0x00006100ff077b82, 0x000fc00000000800, // LDC R7, c[0x0][0x184]
    0x00006200ff087b82, 0x000fc00000000800, // LDC R8, c[0x0][0x188]
    0x000000ff0800720c, 0x000fe20003f05270, // ISETP.NE.AND P0, PT, R8, RZ, PT
    0x00000000fffff984, 0x000fe20000000800, // @!PT LDS RZ, [RZ]
    0x00000000fffff984, 0x000fe20000000800, // @!PT LDS RZ, [RZ]
    0x00000000fffff984, 0x000fe20000000800, // @!PT LDS RZ, [RZ]
    0x00000000fffff984, 0x000fe20000000800, // @!PT LDS RZ, [RZ]
    0x0000000000007992, 0x000fc00000008000, // MEMBAR.ALL.CTA
    0x0000000000007992, 0x000fec0000002000, // MEMBAR.SC.GPU
    0x00000000000079ab, 0x000fc00000000000, // ERRBAR
    0x00000000000075ab, 0x000fec0000000000, // CGAERRBAR
    0x00000000ff00798f, 0x000fe20002000000, // CCTL.IVALL
    0x0000000000608947, 0x000fea0003800000, // @!P0 BRA no_preempt
    0x0000000004007980, 0x000ea40000100900, // LD.E R0, [R4]  (global_exit_flag)
    0x000000ff0000720c, 0x004fda0003f05270, // ISETP.NE.AND P0, PT, R0, RZ, PT
    0x0000000000548947, 0x000fea0003800000, // @!P0 BRA no_preempt
    0x0000000804087980, 0x000ea20000100b00, // LD.E.64 R8, [R4+0x8]  (preempt_idx)
    0x0000007000017945, 0x000fe20003800200, // BSSY.RECONVERGENT B1
    0x000000ff0800720c, 0x004fdc0003f15270, // ISETP.NE.S64.AND P0, PT, R8, RZ, PT
    0x00000000000c8947, 0x000fea0003800000, // @!P0 BRA save_preempt_idx
    0x000000060800720c, 0x000fdc0003f15270, // ISETP.NE.S64.AND P0, PT, R8, R6, PT
    0x0000000000088947, 0x000fea0003800000, // @!P0 BRA save_restore_flag
    0x000000000000794d, 0x000fea0003800000, // EXIT  (kill: another kernel is preempting)
    0x0000000804007385, 0x0001e40000100b06, // ST.E.64 [R4+0x8], R6  (save preempt_idx)
    0x0000000000017941, 0x000fea0003800200, // BSYNC.RECONVERGENT B1
    0x0000000000007919, 0x000e620000002600, // S2R R0, SR_CTAID.Y
    0x0000dd00ff037b82, 0x000e620000000800, // LDC R3, c[0x0][0x374]
    0x0000000000067919, 0x001e620000002500, // S2R R6, SR_CTAID.X
    0x0000000000087919, 0x000e2c0000002700, // S2R R8, SR_CTAID.Z
    0x0000de00ff077b82, 0x000e220000000800, // LDC R7, c[0x0][0x378]
    0x0000000603007224, 0x002fc800078e0200, // IMAD R0, R3, R6, R0
    0x0000000700007224, 0x001fe400078e0208, // IMAD R0, R0, R7, R8
    0x00000001ff077431, 0x000fc600000001ff, // HFMA2 R7, -RZ, RZ, 0, 1.0
    0x0000000400037810, 0x000fca0007ffe000, // IADD3 R3, PT, PT, R0, 0x4, R0
    0x0000000403047825, 0x000fca00078e0004, // IMAD.WIDE.U32 R4, R3, 0x4, R4
    0x0000000404007385, 0x000fe20000100907, // ST.E [R4+0x4], R7  (save block_restore_flag)
    0x000000000000794d, 0x000fea0003800000, // EXIT  (kill: this kernel is preempting)
};

// CU_ETID_ToolsTrapHandler / CU_ETID_ToolsMemory GUIDs recovered from cuxtra's
// static archives (see test/sm120_l3_probe/tools/analyze_cuxtra.py).
static const CUuuid kTrapHandlerEtid = {{ (char)0xcc, (char)0x52, (char)0x9e, (char)0x94,
                                          (char)0x5c, (char)0x4e, (char)0x9d, (char)0x46,
                                          (char)0x83, (char)0x7c, (char)0x96, (char)0x25,
                                          (char)0x86, (char)0x83, (char)0x34, (char)0xe4 }};
static const CUuuid kToolsMemoryEtid = {{ (char)0xbf, (char)0xdb, (char)0x43, (char)0x2d,
                                          (char)0xbf, (char)0x3c, (char)0x5a, (char)0x4a,
                                          (char)0x94, (char)0x5e, (char)0xb3, (char)0x40,
                                          (char)0x29, (char)0xe8, (char)0x1e, (char)0x75 }};

static const size_t kTrapSlotGetInfo     = 20; // fn(ctx, out40)
static const size_t kMemSlotObjGetPc     = 24; // fn(ctx, handle, &pc)
static const size_t kMemSlotObjGetSize   = 25; // fn(handle, &size)

void TarpHandlerSM120::GetTrapHandlerInfo(CUcontext ctx, CUdeviceptr *handler, size_t *size)
{
    // cuxtra's cuXtraGetTrapHandlerInfo only implements the Pascal-era getter
    // (slot 19), which returns error 101 on sm120; call the Blackwell getter
    // (slot 20) through the export table directly instead.
    const void *table = nullptr;
    CUresult res = Driver::GetExportTable(&table, &kTrapHandlerEtid);
    XASSERT(res == CUDA_SUCCESS && table != nullptr,
            "sm120 trap handler export table unavailable (res: %d, table: %p)", res, table);
    const void **trap_table = (const void **)table;
    size_t trap_slots = ((uint64_t)trap_table[0]) / 8;
    XASSERT(trap_slots > kTrapSlotGetInfo && trap_table[kTrapSlotGetInfo] != nullptr,
            "sm120 trap handler getter slot %zu missing (slots: %zu)",
            kTrapSlotGetInfo, trap_slots);

    struct BlackwellTrapInfo
    {
        uint64_t flags;
        uint64_t struct_size;
        void *mem_obj_handle;
        uint64_t stub_offset;
        uint64_t handler_size;
        uint64_t reserved;
    } info;
    memset(&info, 0, sizeof(info));

    typedef CUresult (*TrapInfoFn)(CUcontext, void *);
    res = ((TrapInfoFn)trap_table[kTrapSlotGetInfo])(ctx, &info);
    XASSERT(res == CUDA_SUCCESS && info.mem_obj_handle != nullptr,
            "sm120 trap handler getter failed (res: %d, handle: %p)", res, info.mem_obj_handle);

    const void *mem_table_raw = nullptr;
    res = Driver::GetExportTable(&mem_table_raw, &kToolsMemoryEtid);
    XASSERT(res == CUDA_SUCCESS && mem_table_raw != nullptr,
            "tools memory export table unavailable (res: %d)", res);
    const void **mem_table = (const void **)mem_table_raw;
    size_t mem_slots = ((uint64_t)mem_table[0]) / 8;
    XASSERT(mem_slots > kMemSlotObjGetSize && mem_table[kMemSlotObjGetPc] != nullptr &&
            mem_table[kMemSlotObjGetSize] != nullptr,
            "tools memory resolver slots missing (slots: %zu)", mem_slots);

    // The getter reports the return-stub offset in +0x18; the whole patch
    // design depends on it, so a driver that changes the layout must fail
    // loudly instead of patching a random location.
    XASSERT(info.stub_offset == kTrapPatchOffset,
            "unexpected sm120 trap handler stub offset: 0x%llx (expected 0x%zx)",
            (unsigned long long)info.stub_offset, kTrapPatchOffset);

    uint64_t handler_pc = 0;
    typedef CUresult (*ObjGetPcFn)(CUcontext, void *, uint64_t *);
    res = ((ObjGetPcFn)mem_table[kMemSlotObjGetPc])(ctx, info.mem_obj_handle, &handler_pc);
    XASSERT(res == CUDA_SUCCESS && handler_pc != 0,
            "ObjGetPc failed (res: %d, pc: 0x%llx)", res, (unsigned long long)handler_pc);

    uint64_t handler_size = 0;
    typedef CUresult (*ObjGetSizeFn)(void *, uint64_t *);
    res = ((ObjGetSizeFn)mem_table[kMemSlotObjGetSize])(info.mem_obj_handle, &handler_size);
    XASSERT(res == CUDA_SUCCESS && handler_size >= kTrapPatchOffset + INSTR_LEN,
            "ObjGetSize failed or too small (res: %d, size: 0x%llx)",
            res, (unsigned long long)handler_size);

    XINFO("sm120 trap handler: pc %#llx, size %#llx, stub offset %#llx",
          (unsigned long long)handler_pc, (unsigned long long)handler_size,
          (unsigned long long)info.stub_offset);
    *handler = handler_pc;
    *size = handler_size;
}

void TarpHandlerSM120::SetJumpInstruction(char *instr, const uint64_t jmp_addr)
{
    // BRA (JMP) with a 48-bit absolute target; same encoding as sm86.
    *(uint64_t *)(instr + 0) = 0x345678900000794a;
    *(uint64_t *)(instr + 8) = 0x000fea0003807f12;
    instr[4] = jmp_addr & 0xff;
    instr[5] = (jmp_addr >> 8) & 0xff;
    instr[6] = (jmp_addr >> 16) & 0xff;
    instr[7] = (jmp_addr >> 24) & 0xff;
    instr[8] = (jmp_addr >> 32) & 0xff;
    instr[9] = (jmp_addr >> 40) & 0xff;
}



// ---------------------------------------------------------------------
// Temporary diagnostic hook (experiment scaffolding; env-gated, remove
// after use): XSCHED_SM120_TRAP_TEST_ADDR=<hex> +
// XSCHED_SM120_TRAP_TEST_OFFSET=<hex> patch a minimal signature payload
// [MOV R4/R5=addr][MOV R7=0x5AA5][ST.E [R4],R7] at the given handler offset.
// ---------------------------------------------------------------------
static size_t TrapTestPatchOffset()
{
    const char *env = getenv("XSCHED_SM120_TRAP_TEST_OFFSET");
    return env ? (size_t)strtoull(env, nullptr, 0) : kTrapPatchOffset;
}

static bool BuildTestPayload(uint64_t *words, size_t *nwords)
{
    const char *env = getenv("XSCHED_SM120_TRAP_TEST_ADDR");
    if (env == nullptr) return false;
    uint64_t a = strtoull(env, nullptr, 0);
    if (a == 0) return false;
    words[0] = 0x0000000000147802 | ((uint64_t)(a & 0xffffffffu) << 32);  // MOV R4, lo
    words[1] = 0x000fe20000000f00;
    words[2] = 0x0000000000157802 | ((uint64_t)(a >> 32) << 32);          // MOV R5, hi
    words[3] = 0x000fe20000000f00;
    words[4] = 0x0000000000177802 | (0x5AA5ull << 32);                    // MOV R7, 0x5AA5
    words[5] = 0x000fe20000000f00;
    words[6] = 0x0000000004067385;                                        // ST.E [R4], R7
    words[7] = 0x000fe20000100907;
    *nwords = 8;
    return true;
}

size_t TarpHandlerSM120::GetInjectSize()
{
    uint64_t tmp[8];
    size_t nw = 0;
    if (BuildTestPayload(tmp, &nw)) return nw * 8 + 2 * INSTR_LEN;
    return sizeof(trap_inject_instrs) + 2 * INSTR_LEN;
}

void TarpHandlerSM120::Instrument(void *handler_host, CUdeviceptr handler_dev, size_t size,
                                  void *inject_host, CUdeviceptr inject_dev)
{
    XASSERT(size % INSTR_LEN == 0,
            "trap handler size must be an integer multiple of INSTR_LEN (%d)", INSTR_LEN);
    XASSERT(size >= kTrapPatchOffset + INSTR_LEN,
            "trap handler too small for the sm120 patch site (size: %zu)", size);

    const size_t patch_offset = TrapTestPatchOffset();
    XASSERT(size >= patch_offset + INSTR_LEN, "patch offset %#zx beyond handler size %#zx",
            patch_offset, size);
    uint64_t *handler_instrs = (uint64_t *)handler_host;
    size_t idx = patch_offset / sizeof(uint64_t);

    // the instruction replaced by the jump
    uint64_t replaced_instr[2] = { handler_instrs[idx], handler_instrs[idx + 1] };

    // jump back to the instruction following the replaced one
    char jmp_back_instr[INSTR_LEN];
    SetJumpInstruction(jmp_back_instr, handler_dev + patch_offset + INSTR_LEN);

    uint64_t test_words[8];
    size_t test_nwords = 0;
    size_t arr_size = sizeof(trap_inject_instrs);
    if (BuildTestPayload(test_words, &test_nwords)) {
        arr_size = test_nwords * 8;
        memcpy(inject_host, test_words, arr_size);
        XINFO("sm120 trap TEST payload active at offset %#zx", patch_offset);
    } else {
        memcpy(inject_host, trap_inject_instrs, arr_size);
    }
    // followed by the replaced instruction
    memcpy((char *)inject_host + arr_size, replaced_instr, INSTR_LEN);
    // followed by the jump-back instruction
    memcpy((char *)inject_host + arr_size + INSTR_LEN, jmp_back_instr, INSTR_LEN);

    // jump from the patched instruction to the injected code
    SetJumpInstruction((char *)handler_host + patch_offset, inject_dev);
    XINFO("sm120 trap handler instrumented: patch %#llx -> inject %#llx (replaced %016llx %016llx)",
          (unsigned long long)(handler_dev + patch_offset), (unsigned long long)inject_dev,
          (unsigned long long)replaced_instr[0], (unsigned long long)replaced_instr[1]);
}
