// =====================================================================
//  sm120.cpp - Level-2 (guardian) instruction arrays for Blackwell sm_120
//
//  Generated by tools/instrument/extract_sass.py (T4) from
//  platforms/cuda/hal/inject/inject.cu compiled with
//  nvcc 12.9.41 / ptxas 12.9.41 (-arch sm_120 -m 64 -astoolspatch),
//  then manually reviewed instruction-by-instruction (T5).  Review:
//  test/sm120_mve/T5_REVIEW.md; golden regression: test/sm120_l2_gen/.
//
//    guardian (50 instrs, BSYNC-reconverged at +0x310):
//      LDC R4/R5 @ c[0x0][0x170/0x174]  preempt buffer pointer
//      LDC R6/R7 @ c[0x0][0x180/0x184]  kernel idx
//      (debugger-parameters window c[0x0][0x170..0x188], T1-verified)
//    resume   (32 instrs, keeps the RET.ABS.NODEC R20 exit):
//      LDC R4/R5 @ c[0x0][0x170/0x174]  preempt buffer pointer
//      LDC R20/R21 @ c[0x0][0x178/0x17c]  jump-back entry point
//
//  Resource requirements (T3 review): RequiredRegs = 32, RequiredBarriers = 1.
//
//  Regenerate:
//    cd platforms/cuda/hal/inject && make_msvc.bat ARCH=120 bin dump cc
//    python tools/instrument/extract_sass.py generate --cubin inject_120.cubin
//        --source inject.cu --offset-map sm120 --out-cubin <verify>.cubin
// =====================================================================

#include "xsched/cuda/hal/arch/sm120.h"

using namespace xsched::cuda;

void GuardianSM120::GetGuardianInstructions(const void **guardian_instr, size_t *size)
{
    static const uint64_t guardian_instructions[] =
    {
        0x0000031000007945, 0x000fe80003800200, // BSSY.RECONVERGENT B0, 0x310
        0x00005c00ff047b82, 0x000fc00000000800, // LDC R4, c[0x0][0x170]
        0x00005d00ff057b82, 0x000fc00000000800, // LDC R5, c[0x0][0x174]
        0x0000000000007919, 0x000e220000002500, // S2R R0, SR_CTAID.X
        0x0000dd00ff037b82, 0x000e220000000800, // LDC R3, c[0x0][0x374]
        0x0000000000087919, 0x000e220000002600, // S2R R8, SR_CTAID.Y
        0x00000000000a7919, 0x000e620000002100, // S2R R10, SR_TID.X
        0x00000000000b7919, 0x000e620000002200, // S2R R11, SR_TID.Y
        0x0000000000097919, 0x000ea20000002700, // S2R R9, SR_CTAID.Z
        0x0000000300007224, 0x001fe400078e0208, // IMAD R0, R0, R3, R8
        0x0000000000087919, 0x000e620000002300, // S2R R8, SR_TID.Z
        0x0000de00ff037b82, 0x000ea40000000800, // LDC R3, c[0x0][0x378]
        0x0000000300007224, 0x004fca00078e0209, // IMAD R0, R0, R3, R9
        0x0000000400097810, 0x000fe40007ffe000, // IADD3 R9, PT, PT, R0, 0x4, R0
        0x0000000a08ff7212, 0x002fc6000780fe0b, // LOP3.LUT P0, RZ, R8, R10, R11, 0xfe, !PT
        0x0000000409087825, 0x000fd400078e0004, // IMAD.WIDE.U32 R8, R9, 0x4, R4
        0x0000000000680947, 0x000fea0003800000, // @P0 BRA 0x2b0
        0x0000000004007980, 0x000ea20000100900, // LD.E R0, [R4]
        0x0000013000017945, 0x000fe20003800200, // BSSY.RECONVERGENT B1, 0x260
        0x000000ff0000720c, 0x004fda0003f05270, // ISETP.NE.AND P0, PT, R0, RZ, PT
        0x0000000008008385, 0x0001e200001009ff, // @!P0 ST.E [R8], RZ
        0x00000000003c8947, 0x000fea0003800000, // @!P0 BRA 0x250
        0x00006000ff067b82, 0x000fc00000000800, // LDC R6, c[0x0][0x180]
        0x00006100ff077b82, 0x000fc00000000800, // LDC R7, c[0x0][0x184]
        0x00000001ff037431, 0x000fca00000001ff, // HFMA2 R3, -RZ, RZ, 0, 5.9604644775390625e-08
        0x0000000008007385, 0x0003e80000100903, // ST.E [R8], R3
        0x00000008040a7980, 0x000ea20000100b00, // LD.E.64 R10, [R4+0x8]
        0x0000008000027945, 0x000fe20003800100, // BSSY.RELIABLE B2, 0x240
        0x000000ff0a00720c, 0x004fdc0003f15270, // ISETP.NE.S64.AND P0, PT, R10, RZ, PT
        0x0000000000108947, 0x002fea0003800000, // @!P0 BRA 0x220
        0x000000060a00720c, 0x000fdc0003f15270, // ISETP.NE.S64.AND P0, PT, R10, R6, PT
        0x0000000000020942, 0x000fea0003800100, // @P0 BREAK.RELIABLE B2
        0x0000000000088947, 0x000fea0003800000, // @!P0 BRA 0x230
        0x00000000000c7947, 0x000fea0003800000, // BRA 0x250
        0x0000000804007385, 0x0003e40000100b06, // ST.E.64 [R4+0x8], R6
        0x0000000000027941, 0x000fea0003800100, // BSYNC.RELIABLE B2
        0x0000000408007385, 0x0005e40000100903, // ST.E [R8+0x4], R3
        0x0000000000017941, 0x000fea0003800200, // BSYNC.RECONVERGENT B1
        0x00000000fffff984, 0x000fe20000000800, // @!PT LDS RZ, [RZ]
        0x00000000fffff984, 0x000fe20000000800, // @!PT LDS RZ, [RZ]
        0x00000000fffff984, 0x000fe20000000800, // @!PT LDS RZ, [RZ]
        0x00000000fffff984, 0x000fe20000000800, // @!PT LDS RZ, [RZ]
        0x0000000000007992, 0x000fec0000000000, // MEMBAR.SC.CTA
        0x0000000000007948, 0x000fea0003800000, // WARPSYNC.ALL
        0x0000000000007918, 0x000fe20000000000, // NOP
        0x0000000000007b1d, 0x000fec0000010000, // BAR.SYNC.DEFER_BLOCKING 0x0
        0x0000000008087980, 0x005ea40000100900, // LD.E R8, [R8]
        0x000000ff0800720c, 0x004fda0003f05270, // ISETP.NE.AND P0, PT, R8, RZ, PT
        0x000000000000094d, 0x000fea0003800000, // @P0 EXIT
        0x0000000000007941, 0x000fea0003800200, // BSYNC.RECONVERGENT B0
    };
    *guardian_instr = guardian_instructions;
    *size = sizeof(guardian_instructions);
}

void GuardianSM120::GetResumeInstructions(const void **resume_instr, size_t *size)
{
    static const uint64_t resume_instructions[] =
    {
        0x0000015000007945, 0x000fe80003800200, // BSSY.RECONVERGENT B0, 0x150
        0x00005c00ff047b82, 0x000fc00000000800, // LDC R4, c[0x0][0x170]
        0x00005d00ff057b82, 0x000fc00000000800, // LDC R5, c[0x0][0x174]
        0x0000000000007919, 0x000e220000002500, // S2R R0, SR_CTAID.X
        0x0000dd00ff037b82, 0x000e220000000800, // LDC R3, c[0x0][0x374]
        0x0000000000067919, 0x000e220000002600, // S2R R6, SR_CTAID.Y
        0x0000000000087919, 0x000e6c0000002700, // S2R R8, SR_CTAID.Z
        0x0000de00ff077b82, 0x000e620000000800, // LDC R7, c[0x0][0x378]
        0x0000000300007224, 0x001fc800078e0206, // IMAD R0, R0, R3, R6
        0x0000000700007224, 0x002fca00078e0208, // IMAD R0, R0, R7, R8
        0x0000000500037810, 0x000fca0007ffe000, // IADD3 R3, PT, PT, R0, 0x5, R0
        0x0000000403047825, 0x000fca00078e0004, // IMAD.WIDE.U32 R4, R3, 0x4, R4
        0x0000000004007980, 0x000ea40000100900, // LD.E R0, [R4]
        0x000000ff0000720c, 0x004fda0003f05270, // ISETP.NE.AND P0, PT, R0, RZ, PT
        0x000000000000894d, 0x000fea0003800000, // @!P0 EXIT
        0x0000000000007948, 0x000fea0003800000, // WARPSYNC.ALL
        0x0000000000007918, 0x000fe20000000000, // NOP
        0x0000000000007b1d, 0x000fec0000010000, // BAR.SYNC.DEFER_BLOCKING 0x0
        0x0000000004007385, 0x0001e200001009ff, // ST.E [R4], RZ
        0x00005e00ff147b82, 0x000fc00000000800, // LDC R20, c[0x0][0x178]
        0x00005f00ff157b82, 0x000fc00000000800, // LDC R21, c[0x0][0x17c]
        0x0000000000007941, 0x000fea0003800200, // BSYNC.RECONVERGENT B0
        0x0000000014007950, 0x001fea0003e00000, // RET.ABS.NODEC R20 0x0
        0xfffffffc00fc7947, 0x000fc0000383ffff, // BRA 0x170 (self)
        0x0000000000007918, 0x000fc00000000000, // NOP
        0x0000000000007918, 0x000fc00000000000, // NOP
        0x0000000000007918, 0x000fc00000000000, // NOP
        0x0000000000007918, 0x000fc00000000000, // NOP
        0x0000000000007918, 0x000fc00000000000, // NOP
        0x0000000000007918, 0x000fc00000000000, // NOP
        0x0000000000007918, 0x000fc00000000000, // NOP
        0x0000000000007918, 0x000fc00000000000, // NOP
    };
    *resume_instr = resume_instructions;
    *size = sizeof(resume_instructions);
}
