#pragma once

#include "xsched/cuda/hal/level2/guardian.h"
#include "xsched/cuda/hal/level3/trap.h"

namespace xsched::cuda
{

/// @brief Level-2 (guardian) support for Blackwell sm_120.
/// The instruction arrays are generated by tools/instrument/extract_sass.py
/// and reviewed in test/sm120_mve/T5_REVIEW.md.
class GuardianSM120 : public Guardian
{
public:
    GuardianSM120() = default;
    virtual ~GuardianSM120() = default;

    virtual void GetGuardianInstructions(const void **guardian_instr, size_t *size) override;
    virtual void GetResumeInstructions(const void **resume_instr, size_t *size) override;

    // Hardware-verified floors (test/sm120_mve/T5_REVIEW.md §4):
    // guardian max live register R11, resume R21 (incl. the R20/R21 pair
    // load); one BAR.SYNC per array.  Same values as the sm86 arrays.
    virtual size_t RequiredRegs() override { return 32; }
    virtual size_t RequiredBarriers() override { return 1; }
};

/// @brief Level-3 (trap) support for Blackwell sm_120.
/// Patch site: the return-stub entry at handler offset 0x880 (the driver's
/// slot-20 info reports it as the +0x18 field; the stub is shared by every
/// handler exit path and begins with two NOPs).
class TarpHandlerSM120 : public TarpHandler
{
public:
    TarpHandlerSM120() = default;
    virtual ~TarpHandlerSM120() = default;

    void SetJumpInstruction(char *instr, const uint64_t jmp_addr);
    virtual size_t GetInjectSize() override;
    virtual void Instrument(void *handler_host, CUdeviceptr handler_dev, size_t size,
                            void *inject_host , CUdeviceptr inject_dev) override;
    virtual void GetTrapHandlerInfo(CUcontext ctx, CUdeviceptr *handler, size_t *size) override;
};

} // namespace xsched::cuda
