#pragma once

#include "xsched/cuda/hal/level2/guardian.h"

namespace xsched::cuda
{

/// @brief Level-2 (guardian) support for Blackwell sm_120.
/// The instruction arrays are generated by tools/instrument/extract_sass.py
/// and reviewed in test/sm120_mve/T5_REVIEW.md.  Note that sm_120 has no
/// trap handler (Level-3) support yet: TarpHandlerSM120 is stage three.
class GuardianSM120 : public Guardian
{
public:
    GuardianSM120() = default;
    virtual ~GuardianSM120() = default;

    virtual void GetGuardianInstructions(const void **guardian_instr, size_t *size) override;
    virtual void GetResumeInstructions(const void **resume_instr, size_t *size) override;
};

} // namespace xsched::cuda
