#!/usr/bin/env python3
# =====================================================================
#  gen_arrays.py - emit mve_arrays.h from the reviewed sm120.cpp (T5)
#
#  The MVE must run EXACTLY the arrays that were reviewed and sealed in
#  platforms/cuda/hal/src/arch/sm120.cpp.  This generator parses the
#  arrays out of that file and emits a plain header consumed by
#  mve_main.cpp, so no by-hand copy can drift.
#
#  Usage:  python gen_arrays.py [sm120.cpp] [mve_arrays.h]
# =====================================================================

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_CPP = os.path.join(HERE, '..', '..', 'platforms', 'cuda', 'hal', 'src', 'arch', 'sm120.cpp')
DEFAULT_OUT = os.path.join(HERE, 'mve_arrays.h')


def main():
    cpp = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_CPP
    out = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUT
    txt = open(cpp, encoding='utf-8').read()
    arrays = {}
    for m in re.finditer(r'static const uint64_t (\w+)\[\]\s*=\s*\{(.*?)\};', txt, re.S):
        words = [int(w, 16) for w in re.findall(r'0x[0-9a-fA-F]{16}', m.group(2))]
        arrays[m.group(1)] = words
    assert set(arrays) == {'guardian_instructions', 'resume_instructions'}, arrays.keys()

    lines = [
        '// AUTO-GENERATED by test/sm120_mve/gen_arrays.py from',
        '// platforms/cuda/hal/src/arch/sm120.cpp -- DO NOT EDIT BY HAND.',
        '// Regenerate:  python test/sm120_mve/gen_arrays.py',
        '#pragma once',
        '#include <cstdint>',
        '#include <cstddef>',
        '',
    ]
    for name, words in arrays.items():
        lines.append('static const uint64_t mve_%s[] = {' % name)
        for i in range(0, len(words), 2):
            lines.append('    0x%016x, 0x%016x,' % (words[i], words[i + 1]))
        lines.append('};')
        lines.append('static const size_t mve_%s_size = sizeof(mve_%s);'
                     % (name, name))
        lines.append('')
    open(out, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
    print('wrote %s: guardian %d words, resume %d words'
          % (out, len(arrays['guardian_instructions']), len(arrays['resume_instructions'])))


if __name__ == '__main__':
    main()
